import { getPayloadClient } from '@/lib/payload'
import type { NormalizedCompetition, NormalizedPlayer, NormalizedTeam } from '../types'

// Shared upsert helpers for the "shared foundation" collections (Sports,
// Competitions, Teams, Players) — used by every sport's sync orchestrator
// (src/lib/sports/sync/*.ts). Matching is always by `externalId` scoped to
// `sport` — never externalId alone. Different api-sports.io hosts (football,
// nfl, rugby, formula1, basketball, ...) hand out their own small,
// overlapping id ranges (NFL team ids and F1 constructor ids both start at
// 1), and these collections are shared across every sport, so an unscoped
// match can silently find and overwrite a completely different sport's row.
// That happened for real: an F1 sync clobbered 20 NFL team rows that
// happened to share externalId '1'-'20'. Always filter by sport here.

export const getOrCreateSport = async (name: string, slug: string): Promise<number> => {
  const payload = await getPayloadClient()

  const existing = await payload.find({
    collection: 'sports',
    where: { slug: { equals: slug } },
    limit: 1,
  })
  if (existing.docs[0]) return existing.docs[0].id

  // `slug` is required at the schema level but auto-generated by a
  // beforeValidate hook from `name` — the empty string here just satisfies
  // create()'s type (which doesn't know about hooks); the hook overwrites it.
  const created = await payload.create({ collection: 'sports', data: { name, slug: '' } })
  return created.id
}

export const upsertCompetition = async (
  sportId: number,
  normalized: NormalizedCompetition,
): Promise<number> => {
  const payload = await getPayloadClient()

  const data = {
    name: normalized.name,
    sport: sportId,
    country: normalized.country,
    season: normalized.season,
    externalId: normalized.externalId,
  }

  const existing = await payload.find({
    collection: 'competitions',
    where: { and: [{ externalId: { equals: normalized.externalId } }, { sport: { equals: sportId } }] },
    limit: 1,
  })

  if (existing.docs[0]) {
    // Never touch slug on update — it must stay stable once set (CLAUDE.md
    // §36), even if the provider's name for this competition later changes.
    const updated = await payload.update({ collection: 'competitions', id: existing.docs[0].id, data })
    return updated.id
  }

  const created = await payload.create({ collection: 'competitions', data: { ...data, slug: '' } })
  return created.id
}

export const upsertTeam = async (sportId: number, normalized: NormalizedTeam): Promise<number> => {
  const payload = await getPayloadClient()

  const data = {
    name: normalized.name,
    shortName: normalized.shortName,
    country: normalized.country,
    sport: sportId,
    externalId: normalized.externalId,
  }

  const existing = await payload.find({
    collection: 'teams',
    where: { and: [{ externalId: { equals: normalized.externalId } }, { sport: { equals: sportId } }] },
    limit: 1,
  })

  if (existing.docs[0]) {
    // Never touch slug on update — same reasoning as upsertCompetition above.
    const updated = await payload.update({ collection: 'teams', id: existing.docs[0].id, data })
    return updated.id
  }

  const created = await payload.create({ collection: 'teams', data: { ...data, slug: '' } })
  return created.id
}

export const findTeamIdByExternalId = async (sportId: number, externalId: string): Promise<number | null> => {
  const payload = await getPayloadClient()
  const existing = await payload.find({
    collection: 'teams',
    where: { and: [{ externalId: { equals: externalId } }, { sport: { equals: sportId } }] },
    limit: 1,
  })
  return existing.docs[0]?.id ?? null
}

// Used for F1 drivers, synced into the shared Players collection (an F1
// driver is structurally just an individual-sport player who has a team —
// see NormalizedPlayer in ../types for why this doesn't get its own
// collection).
export const upsertPlayer = async (
  sportId: number,
  normalized: NormalizedPlayer,
): Promise<number> => {
  const payload = await getPayloadClient()

  const teamId = normalized.teamExternalId
    ? await findTeamIdByExternalId(sportId, normalized.teamExternalId)
    : null

  const data = {
    name: normalized.name,
    sport: sportId,
    team: teamId,
    nationality: normalized.nationality,
    externalId: normalized.externalId,
  }

  const existing = await payload.find({
    collection: 'players',
    where: { and: [{ externalId: { equals: normalized.externalId } }, { sport: { equals: sportId } }] },
    limit: 1,
  })

  if (existing.docs[0]) {
    // Never touch slug on update — same reasoning as upsertCompetition above.
    const updated = await payload.update({ collection: 'players', id: existing.docs[0].id, data })
    return updated.id
  }

  const created = await payload.create({ collection: 'players', data: { ...data, slug: '' } })
  return created.id
}

export const findPlayerIdByExternalId = async (sportId: number, externalId: string): Promise<number | null> => {
  const payload = await getPayloadClient()
  const existing = await payload.find({
    collection: 'players',
    where: { and: [{ externalId: { equals: externalId } }, { sport: { equals: sportId } }] },
    limit: 1,
  })
  return existing.docs[0]?.id ?? null
}
