/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    categories: Category;
    tags: Tag;
    articles: Article;
    sports: Sport;
    competitions: Competition;
    teams: Team;
    players: Player;
    'football-matches': FootballMatch;
    'nfl-games': NflGame;
    'rugby-matches': RugbyMatch;
    'f1-races': F1Race;
    'basketball-games': BasketballGame;
    fighters: Fighter;
    'fight-events': FightEvent;
    fights: Fight;
    'affiliate-providers': AffiliateProvider;
    'how-to-watch-guides': HowToWatchGuide;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    sports: SportsSelect<false> | SportsSelect<true>;
    competitions: CompetitionsSelect<false> | CompetitionsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    'football-matches': FootballMatchesSelect<false> | FootballMatchesSelect<true>;
    'nfl-games': NflGamesSelect<false> | NflGamesSelect<true>;
    'rugby-matches': RugbyMatchesSelect<false> | RugbyMatchesSelect<true>;
    'f1-races': F1RacesSelect<false> | F1RacesSelect<true>;
    'basketball-games': BasketballGamesSelect<false> | BasketballGamesSelect<true>;
    fighters: FightersSelect<false> | FightersSelect<true>;
    'fight-events': FightEventsSelect<false> | FightEventsSelect<true>;
    fights: FightsSelect<false> | FightsSelect<true>;
    'affiliate-providers': AffiliateProvidersSelect<false> | AffiliateProvidersSelect<true>;
    'how-to-watch-guides': HowToWatchGuidesSelect<false> | HowToWatchGuidesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO. Avoid generic text like "image" or "photo".
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Auto-generated from "name" if left blank. Used in the page URL — keep it short, lowercase, and hyphenated.
   */
  slug: string;
  avatar?: (number | null) | Media;
  bio?: string | null;
  socialLinks?:
    | {
        platform: 'twitter' | 'instagram' | 'facebook' | 'linkedin' | 'website';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Auto-generated from "name" if left blank. Used in the page URL — keep it short, lowercase, and hyphenated.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Auto-generated from "name" if left blank. Used in the page URL — keep it short, lowercase, and hyphenated.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Auto-generated from "title" if left blank. Used in the page URL — keep it short, lowercase, and hyphenated.
   */
  slug: string;
  /**
   * Short summary shown in article listings, and used as a fallback meta description when no SEO description is set.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage: number | Media;
  author: number | Author;
  category: number | Category;
  /**
   * Type a tag name and press Enter — matches an existing tag, or creates a new one on the spot.
   */
  tags?: (number | Tag)[] | null;
  relatedTeams?: (number | Team)[] | null;
  relatedCompetition?: (number | null) | Competition;
  relatedMatch?: (number | null) | FootballMatch;
  relatedNFLGame?: (number | null) | NflGame;
  relatedFighters?: (number | Fighter)[] | null;
  relatedFightEvent?: (number | null) | FightEvent;
  relatedFight?: (number | null) | Fight;
  publishedAt?: string | null;
  /**
   * Overrides the page title. Falls back to the title above.
   */
  seoTitle?: string | null;
  /**
   * Overrides the meta description. Falls back to the excerpt.
   */
  seoDescription?: string | null;
  /**
   * Only set this if the canonical URL differs from this page's own URL.
   */
  canonicalURL?: string | null;
  /**
   * Falls back to the featured image.
   */
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * Auto-generated from "name" if left blank. Used in the page URL — keep it short, lowercase, and hyphenated.
   */
  slug: string;
  /**
   * e.g. "ARS" — used where space is tight.
   */
  shortName?: string | null;
  logo?: (number | null) | Media;
  country?: string | null;
  sport: number | Sport;
  /**
   * Every competition this team currently plays in.
   */
  competitions?: (number | Competition)[] | null;
  description?: string | null;
  /**
   * The sports data provider's own ID for this record. Set automatically by sync — do not edit.
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sports".
 */
export interface Sport {
  id: number;
  name: string;
  /**
   * Auto-generated from "name" if left blank. Used in the page URL — keep it short, lowercase, and hyphenated.
   */
  slug: string;
  icon?: (number | null) | Media;
  description?: string | null;
  /**
   * Controls ordering when sports are listed together. Lower numbers first.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions".
 */
export interface Competition {
  id: number;
  name: string;
  /**
   * Auto-generated from "name" if left blank. Used in the page URL — keep it short, lowercase, and hyphenated.
   */
  slug: string;
  sport: number | Sport;
  country?: string | null;
  logo?: (number | null) | Media;
  description?: string | null;
  /**
   * e.g. "2025/26"
   */
  season?: string | null;
  /**
   * The sports data provider's own ID for this record. Set automatically by sync — do not edit.
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "football-matches".
 */
export interface FootballMatch {
  id: number;
  homeTeam: number | Team;
  awayTeam: number | Team;
  competition: number | Competition;
  kickoffTime: string;
  venue?: string | null;
  status: 'scheduled' | 'live' | 'finished' | 'postponed' | 'cancelled';
  homeScore?: number | null;
  awayScore?: number | null;
  /**
   * e.g. "Matchweek 5"
   */
  round?: string | null;
  /**
   * e.g. "2025/26"
   */
  season?: string | null;
  preview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Auto-generated from the two teams and kickoff date.
   */
  slug: string;
  /**
   * The sports data provider's own ID for this record. Set automatically by sync — do not edit.
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Shared by both the NFL and NCAA Football competitions — the same sport, different tiers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nfl-games".
 */
export interface NflGame {
  id: number;
  homeTeam: number | Team;
  awayTeam: number | Team;
  competition: number | Competition;
  kickoffTime: string;
  venue?: string | null;
  status: 'scheduled' | 'live' | 'finished' | 'postponed' | 'cancelled';
  homeScore?: number | null;
  awayScore?: number | null;
  /**
   * e.g. "Week 5", "Wild Card", "Super Bowl LX"
   */
  week?: string | null;
  /**
   * e.g. "2025"
   */
  season?: string | null;
  preview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Auto-generated from the two teams and kickoff date.
   */
  slug: string;
  /**
   * The sports data provider's own ID for this record. Set automatically by sync — do not edit.
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fighters".
 */
export interface Fighter {
  id: number;
  name: string;
  /**
   * Auto-generated from "name" if left blank. Used in the page URL — keep it short, lowercase, and hyphenated.
   */
  slug: string;
  photo?: (number | null) | Media;
  /**
   * e.g. Boxing, or a future combat sport such as MMA/UFC.
   */
  sport: number | Sport;
  nationality?: string | null;
  dateOfBirth?: string | null;
  /**
   * e.g. "Heavyweight"
   */
  weightClass?: string | null;
  wins?: number | null;
  losses?: number | null;
  draws?: number | null;
  /**
   * Wins by knockout.
   */
  knockouts?: number | null;
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fight-events".
 */
export interface FightEvent {
  id: number;
  /**
   * e.g. "Fury vs Usyk 2"
   */
  name: string;
  /**
   * Auto-generated from "name" if left blank. Used in the page URL — keep it short, lowercase, and hyphenated.
   */
  slug: string;
  sport: number | Sport;
  date: string;
  /**
   * The arena, e.g. "Kingdom Arena"
   */
  venue?: string | null;
  /**
   * City/region, e.g. "Riyadh, Saudi Arabia"
   */
  location?: string | null;
  status: 'scheduled' | 'live' | 'finished' | 'postponed' | 'cancelled';
  /**
   * e.g. "Top Rank", "Matchroom Boxing"
   */
  promotion?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fights".
 */
export interface Fight {
  id: number;
  event: number | FightEvent;
  fighterA: number | Fighter;
  fighterB: number | Fighter;
  weightClass?: string | null;
  scheduledRounds?: number | null;
  status: 'scheduled' | 'live' | 'finished' | 'postponed' | 'cancelled';
  winner?: (number | null) | Fighter;
  /**
   * "Submission" is here for future MMA/UFC reuse.
   */
  method?:
    | (
        | 'ko'
        | 'tko'
        | 'decision-unanimous'
        | 'decision-split'
        | 'decision-majority'
        | 'submission'
        | 'draw'
        | 'no-contest'
        | 'disqualification'
      )
    | null;
  /**
   * Title(s) on the line, e.g. "WBC Heavyweight Title". Leave blank if none.
   */
  titles?: string | null;
  preview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Auto-generated from the two fighters and the event date.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  name: string;
  /**
   * Auto-generated from "name" if left blank. Used in the page URL — keep it short, lowercase, and hyphenated.
   */
  slug: string;
  photo?: (number | null) | Media;
  sport: number | Sport;
  /**
   * Leave blank for a free agent.
   */
  team?: (number | null) | Team;
  position?: string | null;
  nationality?: string | null;
  dateOfBirth?: string | null;
  bio?: string | null;
  /**
   * The sports data provider's own ID for this record. Set automatically by sync — do not edit.
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rugby-matches".
 */
export interface RugbyMatch {
  id: number;
  homeTeam: number | Team;
  awayTeam: number | Team;
  competition: number | Competition;
  kickoffTime: string;
  venue?: string | null;
  status: 'scheduled' | 'live' | 'finished' | 'postponed' | 'cancelled';
  homeScore?: number | null;
  awayScore?: number | null;
  /**
   * e.g. "Round 1"
   */
  round?: string | null;
  /**
   * e.g. "2025"
   */
  season?: string | null;
  preview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Auto-generated from the two teams and kickoff date.
   */
  slug: string;
  /**
   * The sports data provider's own ID for this record. Set automatically by sync — do not edit.
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "f1-races".
 */
export interface F1Race {
  id: number;
  /**
   * Grand Prix name, e.g. "Bahrain Grand Prix"
   */
  name: string;
  /**
   * The season-level Formula 1 World Championship competition.
   */
  competition: number | Competition;
  circuitName?: string | null;
  circuitCountry?: string | null;
  circuitCity?: string | null;
  date: string;
  status: 'scheduled' | 'live' | 'finished' | 'postponed' | 'cancelled';
  laps?: number | null;
  distance?: string | null;
  /**
   * e.g. "2025"
   */
  season?: string | null;
  /**
   * Finishing order — one row per driver, populated once the race is finished.
   */
  results?:
    | {
        driver: number | Player;
        team?: (number | null) | Team;
        position?: number | null;
        /**
         * e.g. "1:31:44.742" or "+22.457s"
         */
        time?: string | null;
        laps?: number | null;
        /**
         * Starting grid position
         */
        grid?: string | null;
        id?: string | null;
      }[]
    | null;
  preview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Auto-generated from the race name and season.
   */
  slug: string;
  /**
   * The sports data provider's own ID for this record. Set automatically by sync — do not edit.
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "basketball-games".
 */
export interface BasketballGame {
  id: number;
  homeTeam: number | Team;
  awayTeam: number | Team;
  competition: number | Competition;
  tipoffTime: string;
  venue?: string | null;
  status: 'scheduled' | 'live' | 'finished' | 'postponed' | 'cancelled';
  homeScore?: number | null;
  awayScore?: number | null;
  /**
   * e.g. "2025-2026"
   */
  season?: string | null;
  preview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Auto-generated from the two teams and tip-off date.
   */
  slug: string;
  /**
   * The sports data provider's own ID for this record. Set automatically by sync — do not edit.
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-providers".
 */
export interface AffiliateProvider {
  id: number;
  /**
   * e.g. "DAZN", "ESPN+", "Paramount+"
   */
  name: string;
  /**
   * Auto-generated from "name" if left blank. Used in the page URL — keep it short, lowercase, and hyphenated.
   */
  slug: string;
  logo?: (number | null) | Media;
  /**
   * The real destination URL (may already carry an affiliate tracking tag).
   */
  url: string;
  /**
   * Limited to these options on purpose — CLAUDE.md §26 bans deceptive CTAs like "WATCH FREE"; a select field makes that impossible to type in by accident.
   */
  ctaLabel: 'Watch Live' | 'Where to Watch' | 'Check Streaming Options' | 'View Live Sports Options';
  /**
   * Uncheck for a genuinely free/non-monetized broadcaster — keeps the affiliate disclosure accurate rather than overclaiming.
   */
  isAffiliate?: boolean | null;
  /**
   * Short blurb, e.g. "Official global streaming home of UFC".
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-to-watch-guides".
 */
export interface HowToWatchGuide {
  id: number;
  /**
   * e.g. "How to Watch NFL Games in the UK"
   */
  title: string;
  /**
   * Auto-generated from "title" if left blank. Used in the page URL — keep it short, lowercase, and hyphenated.
   */
  slug: string;
  /**
   * Leave blank for a general/multi-sport guide.
   */
  sport?: (number | null) | Sport;
  /**
   * Optional — for a competition-specific guide, e.g. "How to Watch the Premier League".
   */
  competition?: (number | null) | Competition;
  /**
   * e.g. "United States", "United Kingdom", "Worldwide" — streaming access is region-dependent.
   */
  region?: string | null;
  /**
   * Short summary shown in guide listings, and used as a fallback meta description when no SEO description is set.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage: number | Media;
  /**
   * Where viewers can actually watch — each row links to a centrally managed provider.
   */
  streamingOptions: {
    provider: number | AffiliateProvider;
    /**
     * Optional context, e.g. "Includes NFL Sunday Ticket".
     */
    note?: string | null;
    id?: string | null;
  }[];
  /**
   * Highlight this guide on the How to Watch hub page.
   */
  featured?: boolean | null;
  publishedAt?: string | null;
  /**
   * Overrides the page title. Falls back to the title above.
   */
  seoTitle?: string | null;
  /**
   * Overrides the meta description. Falls back to the excerpt.
   */
  seoDescription?: string | null;
  /**
   * Only set this if the canonical URL differs from this page's own URL.
   */
  canonicalURL?: string | null;
  /**
   * Falls back to the featured image.
   */
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Read-only record of what visitors submitted through /contact.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'sports';
        value: number | Sport;
      } | null)
    | ({
        relationTo: 'competitions';
        value: number | Competition;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'football-matches';
        value: number | FootballMatch;
      } | null)
    | ({
        relationTo: 'nfl-games';
        value: number | NflGame;
      } | null)
    | ({
        relationTo: 'rugby-matches';
        value: number | RugbyMatch;
      } | null)
    | ({
        relationTo: 'f1-races';
        value: number | F1Race;
      } | null)
    | ({
        relationTo: 'basketball-games';
        value: number | BasketballGame;
      } | null)
    | ({
        relationTo: 'fighters';
        value: number | Fighter;
      } | null)
    | ({
        relationTo: 'fight-events';
        value: number | FightEvent;
      } | null)
    | ({
        relationTo: 'fights';
        value: number | Fight;
      } | null)
    | ({
        relationTo: 'affiliate-providers';
        value: number | AffiliateProvider;
      } | null)
    | ({
        relationTo: 'how-to-watch-guides';
        value: number | HowToWatchGuide;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  avatar?: T;
  bio?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  category?: T;
  tags?: T;
  relatedTeams?: T;
  relatedCompetition?: T;
  relatedMatch?: T;
  relatedNFLGame?: T;
  relatedFighters?: T;
  relatedFightEvent?: T;
  relatedFight?: T;
  publishedAt?: T;
  seoTitle?: T;
  seoDescription?: T;
  canonicalURL?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sports_select".
 */
export interface SportsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  description?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions_select".
 */
export interface CompetitionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sport?: T;
  country?: T;
  logo?: T;
  description?: T;
  season?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortName?: T;
  logo?: T;
  country?: T;
  sport?: T;
  competitions?: T;
  description?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  sport?: T;
  team?: T;
  position?: T;
  nationality?: T;
  dateOfBirth?: T;
  bio?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "football-matches_select".
 */
export interface FootballMatchesSelect<T extends boolean = true> {
  homeTeam?: T;
  awayTeam?: T;
  competition?: T;
  kickoffTime?: T;
  venue?: T;
  status?: T;
  homeScore?: T;
  awayScore?: T;
  round?: T;
  season?: T;
  preview?: T;
  slug?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nfl-games_select".
 */
export interface NflGamesSelect<T extends boolean = true> {
  homeTeam?: T;
  awayTeam?: T;
  competition?: T;
  kickoffTime?: T;
  venue?: T;
  status?: T;
  homeScore?: T;
  awayScore?: T;
  week?: T;
  season?: T;
  preview?: T;
  slug?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rugby-matches_select".
 */
export interface RugbyMatchesSelect<T extends boolean = true> {
  homeTeam?: T;
  awayTeam?: T;
  competition?: T;
  kickoffTime?: T;
  venue?: T;
  status?: T;
  homeScore?: T;
  awayScore?: T;
  round?: T;
  season?: T;
  preview?: T;
  slug?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "f1-races_select".
 */
export interface F1RacesSelect<T extends boolean = true> {
  name?: T;
  competition?: T;
  circuitName?: T;
  circuitCountry?: T;
  circuitCity?: T;
  date?: T;
  status?: T;
  laps?: T;
  distance?: T;
  season?: T;
  results?:
    | T
    | {
        driver?: T;
        team?: T;
        position?: T;
        time?: T;
        laps?: T;
        grid?: T;
        id?: T;
      };
  preview?: T;
  slug?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "basketball-games_select".
 */
export interface BasketballGamesSelect<T extends boolean = true> {
  homeTeam?: T;
  awayTeam?: T;
  competition?: T;
  tipoffTime?: T;
  venue?: T;
  status?: T;
  homeScore?: T;
  awayScore?: T;
  season?: T;
  preview?: T;
  slug?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fighters_select".
 */
export interface FightersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  sport?: T;
  nationality?: T;
  dateOfBirth?: T;
  weightClass?: T;
  wins?: T;
  losses?: T;
  draws?: T;
  knockouts?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fight-events_select".
 */
export interface FightEventsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sport?: T;
  date?: T;
  venue?: T;
  location?: T;
  status?: T;
  promotion?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fights_select".
 */
export interface FightsSelect<T extends boolean = true> {
  event?: T;
  fighterA?: T;
  fighterB?: T;
  weightClass?: T;
  scheduledRounds?: T;
  status?: T;
  winner?: T;
  method?: T;
  titles?: T;
  preview?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-providers_select".
 */
export interface AffiliateProvidersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  url?: T;
  ctaLabel?: T;
  isAffiliate?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-to-watch-guides_select".
 */
export interface HowToWatchGuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sport?: T;
  competition?: T;
  region?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  streamingOptions?:
    | T
    | {
        provider?: T;
        note?: T;
        id?: T;
      };
  featured?: T;
  publishedAt?: T;
  seoTitle?: T;
  seoDescription?: T;
  canonicalURL?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  heading: string;
  intro: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Shown on the page, and used as the reply-to address context for submissions.
   */
  contactEmail: string;
  /**
   * Overrides the page title. Falls back to the title above.
   */
  seoTitle?: string | null;
  /**
   * Overrides the meta description. Falls back to the excerpt.
   */
  seoDescription?: string | null;
  /**
   * Only set this if the canonical URL differs from this page's own URL.
   */
  canonicalURL?: string | null;
  /**
   * Falls back to the featured image.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  contactEmail?: T;
  seoTitle?: T;
  seoDescription?: T;
  canonicalURL?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}